BASE_MAP = {
    "(2, 5) cyclic": "",
    "(2, 5, 20) cyclic": "",
    "(quinternary)": "quinary",
    "-2": "binary",
    "-5": "quinary",
    "-five": "quinary",
    "-six": "senary",
    "2-cycle": "",
    "5, 20": "quinary/vigesimal",
    "5-20": "quinary/vigesimal",
    "5-cycle": "",
    "7-vowel Bantu": "",
    "8": "octal",
    "14": "",
    "20": "vigesimal",
    "24": "tetravigesimal",
    "27": "body",
    "80": "",
    "a peculiar": "",
    "a vigesimal": "vigesimal",
    "Bantufive": "quinary",
    "basic vigesimal": "vigesimal",
    "binary": "binary",
    "body": "body",
    "body tally": "body",
    "body-part": "body",
    "body-part tally": "body",
    "body-tally": "body",
    "complex": "",
    "complex vigesimal": "vigesimal",
    "complextwenty": "vigesimal",
    "complicated": "",
    "d 35 body tally": "body",
    "d five-twenty": "quinary/vigesimal",
    "decimal": "decimal",
    "decimal of": "decimal",
    "deimal": "decimal",
    "decimal/vigesimal": "decimal/vigesimal",
    "digit-tally": "body",
    "duodecimal": "duodecimal",
    "five": "quinary",
    "five-": "quinary",
    "five-(quinternary)": "quinary",
    "five-and twenty-": "quinary/vigesimal",
    "five-d": "quinary",
    "hand": "",
    "hands": "",
    "has a vigesimal": "vigesimal",
    "ing": "",
    "modulo 24": "",
    "new decimal": "",
    "one,two,three,many": "",
    "partial quinary": "",
    "peculiar": "",
    "peculiar vigesimal": "vigesimal",
    "politeness": "decimal",
    "poor": "",
    "quaternary": "quaternary",
    "quianry, decimal": "quinary/decimal",
    "quianry, vigesimal": "quinary/vigesimal",
    "quianry-decimal": "quinary/decimal",
    "quinary": "quinary",
    "quinary (5)": "quinary",
    "quinary / decimal": "quinary/decimal",
    "quinary / vigesimal": "quinary/vigesimal",
    "quinary /decimal": "quinary/decimal",
    "quinary /vigesimal": "quinary/vigesimal",
    "quinary, decimal": "quinary/decimal",
    "quinary, vigesimal": "quinary/vigesimal",
    "quinary,-twenty": "quinary/vigesimal",
    "quinary-decimal": "quinary/decimal",
    "quinary-vigesimal": "quinary/vigesimal",
    "quinary/vigesimal": "quinary/vigesimal",
    "quinary/ decimal": "quinary/decimal",
    "quinary/decimal": "quinary/decimal",
    "quintenary": "quinary",
    "regular decimal": "decimal",
    "senary": "senary",
    "similar": "",
    "similar decimal": "",
    "six-": "senary",
    "six-cycle": "",
    "sixty": "body",
    "special": "",
    "special aboriginal": "",
    "tally": "",
    "ten": "decimal",
    "ten-d": "decimal",
    "twenty": "vigesimal",
    "two": "binary",
    "two-": "binary",
    "vegisimal": "vigesimal",
    "very": "",
    "very complex": "",
    "very particular": "",
    "very unusual": "",
    "vigesimal": "vigesimal",
    "vigesimal or20": "vigesimal",
    "vigesimal/decimal": "decimal/vigesimal",
    "–25": "pentavigesimal",
}